version: '3.8'
services:
  server:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
