const item = {
  id: 'MLA897322892',
  site_id: 'MLA',
  title: 'iPhone 11 64 Gb Blanco',
  seller: {
    id: 79467935,
    permalink: 'http://perfil.mercadolibre.com.ar/NTECHNOLOGY',
    registration_date: '2005-03-24T15:52:24.000-04:00',
    car_dealer: false,
    real_estate_agency: false,
    tags: [
      'normal',
      'user_info_verified',
      'eshop',
      'credits_profile',
      'credits_priority_2',
      'mshops',
      'messages_as_seller',
      'messages_as_buyer',
    ],
    eshop: {
      nick_name: 'NTECHNOLOGY',
      eshop_rubro: null,
      eshop_id: 453858,
      eshop_locations: [],
      site_id: 'MLA',
      eshop_logo_url: 'http://resources.mlstatic.com/eshops/79467935v5dfa45.png',
      eshop_status_id: 1,
      seller: 79467935,
      eshop_experience: 0,
    },
    seller_reputation: {
      transactions: {
        total: 254,
        canceled: 11,
        period: 'historic',
        ratings: {
          negative: 0,
          positive: 1,
          neutral: 0,
        },
        completed: 243,
      },
      power_seller_status: null,
      metrics: {
        claims: {
          rate: 0,
          value: 2,
          period: '365 days',
        },
        delayed_handling_time: {
          rate: 0,
          value: 0,
          period: '365 days',
        },
        sales: {
          period: '365 days',
          completed: 243,
        },
        cancellations: {
          rate: 0,
          value: 1,
          period: '365 days',
        },
      },
      level_id: '5_green',
    },
  },
  price: 157999,
  prices: {
    id: 'MLA897322892',
    prices: [
      {
        id: '20',
        type: 'standard',
        conditions: {
          context_restrictions: [],
          start_time: null,
          end_time: null,
          eligible: true,
        },
        amount: 157999,
        regular_amount: null,
        currency_id: 'ARS',
        exchange_rate_context: 'DEFAULT',
        metadata: {},
        last_updated: '2021-02-11T17:18:35Z',
      },
    ],
    presentation: {
      display_currency: 'ARS',
    },
    payment_method_prices: [],
  },
  sale_price: null,
  currency_id: 'ARS',
  available_quantity: 3,
  sold_quantity: 4,
  buying_mode: 'buy_it_now',
  listing_type_id: 'gold_special',
  stop_time: '2040-11-10T04:00:00.000Z',
  condition: 'new',
  permalink: 'https://www.mercadolibre.com.ar/iphone-11-64-gb-blanco/p/MLA15149562',
  thumbnail: 'http://http2.mlstatic.com/D_641268-MLA43654417348_102020-I.jpg',
  thumbnail_id: '641268-MLA43654417348_102020',
  accepts_mercadopago: true,
  installments: {
    quantity: 12,
    amount: 22405.57,
    rate: 70.17,
    currency_id: 'ARS',
  },
  address: {
    state_id: 'AR-C',
    state_name: 'Capital Federal',
    city_id: 'TUxBQlZJTDc4MDda',
    city_name: 'Villa del Parque',
  },
  shipping: {
    free_shipping: true,
    mode: 'me2',
    tags: ['self_service_in', 'mandatory_free_shipping'],
    logistic_type: 'xd_drop_off',
    store_pick_up: false,
  },
  seller_address: {
    id: '',
    comment: '',
    address_line: '',
    zip_code: '',
    country: {
      id: 'AR',
      name: 'Argentina',
    },
    state: {
      id: 'AR-C',
      name: 'Capital Federal',
    },
    city: {
      id: 'TUxBQlZJTDc4MDda',
      name: 'Villa del Parque',
    },
    latitude: '',
    longitude: '',
  },
  attributes: [
    {
      name: 'Marca',
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
      source: 1,
      id: 'BRAND',
      value_id: '9344',
      value_name: 'Apple',
      value_struct: null,
      values: [
        {
          struct: null,
          source: 1,
          id: '9344',
          name: 'Apple',
        },
      ],
    },
    {
      value_name: 'Apple GPU MP4',
      value_struct: null,
      source: 1,
      id: 'GPU_MODEL',
      name: 'Modelo de GPU',
      value_id: '7740544',
      values: [
        {
          id: '7740544',
          name: 'Apple GPU MP4',
          struct: null,
          source: 1,
        },
      ],
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
    },
    {
      values: [
        {
          struct: null,
          source: 1505,
          id: '2230284',
          name: 'Nuevo',
        },
      ],
      name: 'Condición del ítem',
      value_id: '2230284',
      value_name: 'Nuevo',
      value_struct: null,
      id: 'ITEM_CONDITION',
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
      source: 1505,
    },
    {
      name: 'Línea',
      value_id: '58993',
      value_name: 'iPhone',
      values: [
        {
          id: '58993',
          name: 'iPhone',
          struct: null,
          source: 1,
        },
      ],
      attribute_group_name: 'Otros',
      source: 1,
      id: 'LINE',
      attribute_group_id: 'OTHERS',
      value_struct: null,
    },
    {
      name: 'Modelo',
      value_struct: null,
      values: [
        {
          id: '7739079',
          name: 'iPhone 11',
          struct: null,
          source: 1,
        },
      ],
      attribute_group_name: 'Otros',
      id: 'MODEL',
      value_id: '7739079',
      value_name: 'iPhone 11',
      attribute_group_id: 'OTHERS',
      source: 1,
    },
    {
      values: [
        {
          name: 'Apple A13 Bionic',
          struct: null,
          source: 1,
          id: '7740540',
        },
      ],
      attribute_group_name: 'Otros',
      source: 1,
      id: 'PROCESSOR_MODEL',
      name: 'Modelo del procesador',
      value_id: '7740540',
      value_name: 'Apple A13 Bionic',
      value_struct: null,
      attribute_group_id: 'OTHERS',
    },
    {
      name: 'Peso',
      attribute_group_id: 'OTHERS',
      source: 1,
      id: 'WEIGHT',
      value_name: '194 g',
      value_struct: {
        number: 194,
        unit: 'g',
      },
      values: [
        {
          id: '2583040',
          name: '194 g',
          struct: {
            number: 194,
            unit: 'g',
          },
          source: 1,
        },
      ],
      attribute_group_name: 'Otros',
      value_id: '2583040',
    },
  ],
  original_price: null,
  category_id: 'MLA1055',
  official_store_id: null,
  domain_id: 'MLA-CELLPHONES',
  catalog_product_id: 'MLA15149562',
  tags: ['brand_verified', 'good_quality_picture', 'immediate_payment', 'cart_eligible', 'shipping_guaranteed'],
  catalog_listing: true,
  order_backend: 1,
};
